name: Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: login ghcr
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: build image
      run: docker build -t ghcr.io/${{ github.actor }}/vue-demo:latest .

    - name: push image
      run: docker push ghcr.io/${{ github.actor }}/vue-demo:latest

    - name: deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ghcr.io/${{ github.actor }}/vue-demo:latest

          docker stop vue-demo || true
          docker rm vue-demo || true

          docker run -d \
            -p 8089:80 \
            --name vue-demo \
            ghcr.io/${{ github.actor }}/vue-demo:latest